apiVersion: apps/v1beta2
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    field.cattle.io/creatorId: user-8q5fs
    field.cattle.io/publicEndpoints: "null"
  creationTimestamp: null
  generation: 1
  labels:
    workload.user.cattle.io/workloadselector: deployment-czjd-admin
  name: admin
  selfLink: /apis/apps/v1beta2/namespaces/czjd/deployments/admin
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-czjd-admin
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        workload.cattle.io/state: '{"eXdub2RlNDA=":"c-b8288:m-a95baf60eee1","eXdub2RlNDE=":"c-b8288:m-31c1606306ac"}'
      creationTimestamp: null
      labels:
        workload.user.cattle.io/workloadselector: deployment-czjd-admin
    spec:
      containers:
      - image: tangram/admin:3.3.1.2
        imagePullPolicy: IfNotPresent
        name: admin
        resources:
          limits:
            memory: 20Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities: {}
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
      dnsPolicy: ClusterFirst
      nodeName: ywnode40
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
