apiVersion: apps/v1beta2
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
    field.cattle.io/creatorId: user-8q5fs
    field.cattle.io/publicEndpoints: '[{"addresses":["59.202.31.40"],"port":32688,"protocol":"TCP","serviceName":"czjd:mosaic-nodeport","allNodes":true}]'
  creationTimestamp: null
  generation: 1
  labels:
    workload.user.cattle.io/workloadselector: deployment-czjd-mosaic
  name: mosaic
  selfLink: /apis/apps/v1beta2/namespaces/czjd/deployments/mosaic
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-czjd-mosaic
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        field.cattle.io/ports: '[[{"containerPort":80,"dnsName":"mosaic-nodeport","kind":"NodePort","name":"80tcp1","protocol":"TCP","sourcePort":32688}]]'
        workload.cattle.io/state: '{"eXdub2RlNDA=":"c-b8288:m-a95baf60eee1","eXdub2RlNDE=":"c-b8288:m-31c1606306ac"}'
      creationTimestamp: null
      labels:
        workload.user.cattle.io/workloadselector: deployment-czjd-mosaic
    spec:
      containers:
      - image: tangram/mosaic:3.3.1.14
        imagePullPolicy: IfNotPresent
        name: mosaic
        ports:
        - containerPort: 80
          name: 80tcp1
          protocol: TCP
        resources:
          limits:
            memory: 128Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities: {}
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
        volumeMounts:
        - mountPath: /usr/share/nginx/html/modules
          name: vol1
      dnsPolicy: ClusterFirst
      nodeName: ywnode41
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /opt/data/mosaic/modules
          type: DirectoryOrCreate
        name: vol1
status: {}
