apiVersion: apps/v1beta2
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
    field.cattle.io/creatorId: user-8q5fs
    field.cattle.io/publicEndpoints: "null"
  creationTimestamp: null
  generation: 1
  labels:
    workload.user.cattle.io/workloadselector: deployment-czjd-web-server
  name: web-server
  selfLink: /apis/apps/v1beta2/namespaces/czjd/deployments/web-server
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-czjd-web-server
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        workload.cattle.io/state: '{"eXdub2RlNDE=":"c-b8288:m-31c1606306ac"}'
      creationTimestamp: null
      labels:
        workload.user.cattle.io/workloadselector: deployment-czjd-web-server
    spec:
      containers:
      - env:
        - name: SHORT_MSG_PASSWORD
          value: Aa654321
        - name: SHORT_MSG_SERVER
          value: http://172.17.58.66
        - name: COS3_DATASOURCE_PASSWORD
          value: czjd_123
        - name: COS3_DATASOURCE_URL
          value: jdbc:mysql://59.202.61.166:3306/czjd?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false
        - name: COS3_DATASOURCE_USERNAME
          value: czjd
        - name: COS3_KETTLE_HOST
          value: 59.202.61.166
        - name: SHORT_MSG_APPID
          value: "062"
        image: tangram/cos3-web-server:3.3.1.20
        imagePullPolicy: IfNotPresent
        name: web-server
        resources:
          limits:
            memory: 2Gi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities: {}
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
        volumeMounts:
        - mountPath: /modules
          name: vol1
        - mountPath: /opt/upload/cos3
          name: vol2
      dnsPolicy: ClusterFirst
      nodeName: ywnode41
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /opt/data/mosaic/modules
          type: DirectoryOrCreate
        name: vol1
      - hostPath:
          path: /opt/data/upload/cos3
          type: DirectoryOrCreate
        name: vol2
status: {}
