apiVersion: v1
kind: Service
metadata:
  annotations:
    field.cattle.io/targetWorkloadIds: '["deployment:czjd:admin"]'
    workload.cattle.io/targetWorkloadIdNoop: "true"
    workload.cattle.io/workloadPortBased: "true"
  creationTimestamp: null
  name: admin
  ownerReferences:
  - apiVersion: apps/v1beta2
    controller: true
    kind: deployment
    name: admin
    uid: 1aecd5e6-4083-11e9-84ff-00163e000729
  selfLink: /api/v1/namespaces/czjd/services/admin
spec:
  clusterIP: None
  ports:
  - name: default
    port: 42
    protocol: TCP
    targetPort: 42
  selector:
    workload.user.cattle.io/workloadselector: deployment-czjd-admin
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
