apiVersion: v1
kind: Service
metadata:
  annotations:
    field.cattle.io/targetWorkloadIds: '["deployment:czjd:mosaic"]'
    workload.cattle.io/targetWorkloadIdNoop: "true"
    workload.cattle.io/workloadPortBased: "true"
  creationTimestamp: null
  name: mosaic
  ownerReferences:
  - apiVersion: apps/v1beta2
    controller: true
    kind: deployment
    name: mosaic
    uid: 2b18d5b2-4083-11e9-84ff-00163e000729
  selfLink: /api/v1/namespaces/czjd/services/mosaic
spec:
  clusterIP: None
  ports:
  - name: 80tcp1-mosaic
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    workload.user.cattle.io/workloadselector: deployment-czjd-mosaic
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
